<section class="hero is-dark is-bold">
    <div class="hero is-dark is-bold">
<div class="hero-body">
<div class="container has-text-centered">
    <img src="../images/protech-the-computer-guys.png" alt="Our Protech logo" title="Protech, The Computer Guys" id="logo">
</div>
</div>
<div class="is-hidden-desktop">
    <p class="title has-text-centered" id="margin-top-10px">Protech: The Computer Guys</p>
</div>
<p class="subtitle has-text-centered">109 South Davis Avenue &#8901; Cleveland, MS &#8901; 662-545-3465</p>
<div class="hero-foot">
    <div class="level">
        <div class="level-right is-hidden-mobile">
            <a class="icon is-medium" href="https://www.facebook.com/Myputerguys/" target="_blank">
                <i class="fa fa-facebook-official has-text-centered" aria-hidden="true"></i>
            </a>
        </div>
    <nav class="nav is-shadowed">
        <ul class="nav-right nav-menu" id="navbar">
            <li><span class="icon is-hidden-desktop"><i class="fa fa-home" aria-hidden="true"></i></span><a class="nav-item is-tab" href="../index.php">Home</a></li>
            <li><span class="icon is-hidden-desktop"><i class="fa fa-shopping-basket" aria-hidden="true"></i></span><a class="nav-item is-tab" href="index.php">In-Store Services</a>
                <div class="drop-down-container">
                    <ul class="drop-down">
                        <li><a class="button is-success" href="cleaning.php">PC/Mac Cleaning</a></li>
                        <li><a class="button is-success" href="data.php">Data Transfer/Recovery</a></li>
                        <li><a class="button is-success" href="">PC/Mac Repair</a></li>
                        <li><a class="button is-success" href="iphone_repair.php">iPhone Repair</a></li>
                    </ul>
                </div>
            </li>
            <li><span class="icon is-hidden-desktop"><i class="fa fa-building" aria-hidden="true"></i></span><a class="nav-item is-tab">Buisness Services</a></li>
            <li><span class="icon is-hidden-desktop"><i class="fa fa-home" aria-hidden="true"></i></span><a class="nav-item is-tab" href="../location.php">Our Location</a></li>
            <li><span class="icon is-hidden-desktop"><i class="fa fa-building" aria-hidden="true"></i></span><a class="nav-item is-tab" href="../gps-login.php">Client Services </a>
                <div class="drop-down-container">
                        <ul class="drop-down">
                            <li><span class="icon is-hidden-desktop"><i class="fa fa-phone" aria-hidden="true"></i></span><a class="button is-success" href="http://www.voip.a-pro-tech.com">VoIP Login</a></li>
                            <li><span class="icon is-hidden-desktop"><i class="fa fa-phone" aria-hidden="true"></i></span><a class="button is-success" href="../gps-login.php">GPS Tracking Login</a></li>
                        </ul>
                    </div>
                </li>                       
            <li><span class="icon is-hidden-desktop"><i class="fa fa-address-card-o" aria-hidden="true"></i></span><a class="nav-item is-tab" id=contactbutton href="../contact.php">Contact</a></li>
        </ul>
        
        <div class="nav-toggle" onclick="navtoggle()" id="navtoggle">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </nav>
</div>
</div>
</div>
</section>