<section>
        <div class="hero is-dark is-bold">
            <div class="hero-body">
                <div class="columns is-v-centered">
                    <div class="column is-4"></div>
                  <div class="column has-text-centered">
                    <img class="image" id="logo" src="images/protech-the-computer-guys.png" alt="Our Protech logo" title="Protech, The Computer Guys" >
                  </div>
                  <div class="column has-text-centered" id="phonenumber">
                    <h1 class="title is-4">Call us at <br class="is-hidden-touch">662-545-3465</h1>
                  </div>  
                </div>
            </div>
            <div class="hero-foot">
                    <nav class="nav">
                        <div class="nav-toggle" onclick="navtoggle()" id="navtoggle">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                        <ul class="nav-right nav-menu" id="navbar">                
                            <li><span class="icon is-hidden-desktop"><i class="fa fa-home" aria-hidden="true"></i></span><a class="nav-item is-tab" href="index.php">Home</a></li> 
                            <li><span class="icon is-hidden-desktop"><i class="fa fa-shopping-basket" aria-hidden="true"></i></span><a class="nav-item is-tab" href="instore/index.php">In-Store Services</a>
                                <div class="drop-down-container">
                                    <ul class="drop-down is-overlay">
                                        <li><a class="button is-success" href="instore/cleaning.php">PC/Mac Cleaning</a></li>
                                        <li><a class="button is-success" href="instore/computer_repair.php">PC/Mac Repair</a></li>
                                        <li><a class="button is-success" href="instore/data.php">Data Transfer/Recovery</a></li>
                                        <li><a class="button is-success" href="instore/iphone_repair.php">iPhone Repair</a></li>
                                    </ul>
                                </div>
                            </li>
                            
                            <li><span class="icon is-hidden-desktop"><i class="fa fa-home" aria-hidden="true"></i></span><a class="nav-item is-tab" href="location.php">Our Location</a></li>
                           
                            <li><span class="icon is-hidden-desktop"><i class="fa fa-building" aria-hidden="true"></i></span><a class="nav-item is-tab" href="gps-login.php">Client Services </a>
                                <div class="drop-down-container">
                                        <ul class="drop-down">
                                            <li><span class="icon is-hidden-desktop"><i class="fa fa-phone" aria-hidden="true"></i></span><a class="button is-success" href="http://www.voip.a-pro-tech.com">VoIP Login</a></li>
                                            <li><span class="icon is-hidden-desktop"><i class="fa fa-phone" aria-hidden="true"></i></span><a class="button is-success" href="gps-login.php">GPS Tracking Login</a></li>
                                        </ul>
                                    </div>
                                </li>
                            <li><span class="icon is-hidden-desktop"><i class="fa fa-address-card-o" aria-hidden="true"></i></span><a class="nav-item is-tab" id=contactbutton href="../contact.php">Contact</a></li>
                        </ul>
                    </nav>
                
            </div>
        </div>
    </section>